### ISSUE TITLE
 async def courses_list(req, res):SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by YKNB** [florimondmanca/ng-courses#1]
from bocadillo import App

app = App(
    enable_cors=True,
    cors_config={"allow_origins": ["*"], "allow_methods": ["*"]},
)

_COURSES = [
    {
        "id": 1,
        "code": "adv-maths",
        "name": "Advanced Mathematics",
        "created": "2018-08-14T12:09:45",
    },
    {
        "id": 2,
        "code": "cs1",
        "name": "Computer Science I",
        "created": "2018-06-12T18:34:16",
    },
]

@app.route("/courses")
async def courses_list(req, res):
    res.media = _COURSES

if __name__ == "__main__":
    app.run()

**Comment by YKNB** [comment]
File "app.py", line 25
    async def courses_list(req, res):
        ^
SyntaxError: invalid syntax

**Comment by florimondmanca** [comment]
Hi @YKNB,

From the `SyntaxError` pointing to `async def`, it seems that your version of Python does not support the `async/await` syntax. Which version of Python are you using?

P.S.: I am being understanding here, but be aware that simply copy/pasting some code in this manner may come across as rude to some. I wouldn't have minded you putting in some sentences describing your issues. :-)

**Comment by florimondmanca** [comment]
I just released a fix in v0.12.1 that enforces that Python 3.6+ is installed on the target machine to be able to install Bocadillo. Can you try upgrading to see if your Python version is the problem?

```bash
pip install -U bocadillo
```

**Comment by YKNB** [comment]
sorry I do not usually comment on a bug code

**Comment by YKNB** [comment]
sorry it was the version of the python since I use a mac due blow I have two version, the Python 2.7 and Python 3.7.2 ..thank you again

**Comment by florimondmanca** [comment]
Alright! Glad this worked out. :+1:
